---
title: "Instructor's Guide: Teaching Probability"
author:
  - "Emily Bolger, bolgerem@msu.edu"
  - "Mark Branson, mbranson@stevenson.edu"
  - "Nathan Alexander, nathan.alexander@howard.edu"
output: html_document
date: "2025-07-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Overivew

Students are introduced to the foundations of probability with relevant examples that provide opportunities for instructors to switch between classical mathematical cases and more context-specific examples. Here we provide notes for instructors.

This document is based on the facilitation guide developed by Bolger and Roca, probability notes by ...., code by all.

Ref #sec-norms

# Learning Objectives

# Context

## Fair hiring practices and the issue of gender

The chapter begins with an example on fair hiring practices.

Describe here the example:
80 pct men, 20 pct women
10 slots avail in large company

1. why is the applicant pool skewed differently that the population?

provide resources and mention to students information women's rights (provided references and links to -- use .bib file)
  
## Why is this problem important?


# Content

2. if the applicants are equally qualified what is the probability of...
  - hiring a man? hiring a woman?

$$

$$



# Code

# References










